<?php

namespace Database\Seeders;

use App\Models\Orgao;
use App\Models\Origem;
use Illuminate\Database\Seeder;

class OrgaoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $orgaos = [
            [
                'id_origem' => 2,
                'cod_orgao' => 11,
                'nome' => 'SEC. EDUCAÇÃO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 13,
                'nome' => 'SEC. FAZENDA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 83,
                'nome' => 'AGENCIA ESTADUAL DE DEFESA AGROPECUARIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 81,
                'nome' => 'AGERBA - AGENCIA DE REGULAM. DE ENERGIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 4,
                'nome' => 'SEC. DE PROMOCAO DA IGUALDADE - SEPROMI',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 86,
                'nome' => 'BAPREV - INATIVOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 14,
                'nome' => 'CASA CIVIL',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 5,
                'nome' => 'CASA MILITAR',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 89,
                'nome' => 'CBMBA - CORPO DE BOMBEIROS MILITAR DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 36,
                'nome' => 'CBPM - CIA. BAIANA DE PESQUISA MINERAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 45,
                'nome' => 'CENTRO DE RECURSOS AMBIENTAIS',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 40,
                'nome' => 'CENTRO INDUSTRIAL DO SUBAE',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 38,
                'nome' => 'CEPED - CENTRO DE PESQUISA E DESENV.',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 43,
                'nome' => 'CIA DE DESENVOLVIMENTO URBANO DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 35,
                'nome' => 'COMPANHIA DE DESENVOLVIMENTO DE ACAO REGIONAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 47,
                'nome' => 'DEPARTAMENTO DE INFRA ESTRUTURA DE TRANSP. BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 49,
                'nome' => 'DEPARTAMENTO ESTADUAL DE TRANSITO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 50,
                'nome' => 'EBAL EMPRESA BAIANA DE ALIMENTOS S.A',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 51,
                'nome' => 'EMPRESA BAIANA DE DESENVOLVIMENTO AGRÍCOLA S.A',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 33,
                'nome' => 'EMPRESA DE TURISMO DA BAHIA S.A.',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 52,
                'nome' => 'EMPRESA GRAFICA DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 54,
                'nome' => 'FUNDACAO CULTURAL DO EST. DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 55,
                'nome' => 'FUNDACAO DA CRIANCA E DO ADOLECENTE',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 58,
                'nome' => 'FUNDACAO ESCOLA DE SERVICOS PUBLICOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 56,
                'nome' => 'FUNDACAO HEMATOLOGIA E HEMOTERAPIA DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 57,
                'nome' => 'FUNDAÇÃO PEDRO CALMON',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 87,
                'nome' => 'FUNPREV-APOSENTADOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 78,
                'nome' => 'FUNPREV - PENSAO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 95,
                'nome' => 'FUNPREV-AGUARDANDO APOSENTADORIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 1,
                'nome' => 'GABINETE DO GOVERNADOR',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 1012,
                'nome' => 'GABINETE DO VICE GOVERNADOR',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 46,
                'nome' => 'INEMA - INSTITUTO DO MEIO AMBIENTE E RECURSOS HÍDRICO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 80,
                'nome' => 'INST. BAIANA DE METROL. NORM. QUAI. IND.',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 61,
                'nome' => 'INST. DE TERRAS DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 62,
                'nome' => 'INST. PATRIMONIO ARTISTICO E CULTURAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 60,
                'nome' => 'INSTITUTO DE ARTESANATO VISCONDE DE MAUA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 63,
                'nome' => 'IRDEB-INST. DE RADIOFUSAO DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 64,
                'nome' => 'JUNTA COMERCIAL DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 59,
                'nome' => 'PLANSERV',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 12,
                'nome' => 'POLICIA CIVIL',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 30,
                'nome' => 'POLICIA MILITAR',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 6,
                'nome' => 'PROCURADORIA GERAL DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 65,
                'nome' => 'PRODEB-CIA DE PRO DE DADOS ESTADO BA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 9,
                'nome' => 'SEC. ADMINISTRACAO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 23,
                'nome' => 'SEC. ADMINISTRAÇÃO PENITENCIÁRIA E RESSOCIALIZAÇÃO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 10,
                'nome' => 'SEC. AGRICULTURA IRRIG. F REF. AGRARIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 22,
                'nome' => 'SEC. CULTURA E TURISMO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 25,
                'nome' => 'SEC. DE COMBATE À POBREZA E DESIGUALDADES',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 77,
                'nome' => 'SEC. DE DESENVOLVIMENTO RURAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 24,
                'nome' => 'SEC. DE INFRA-ESTRUTURA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 82,
                'nome' => 'SEC. DE JUSTIÇA DIREITOS HUMANOS E DESENV. SOCIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 27,
                'nome' => 'SEC. DE MEIO AMBIENTE E RECURSOS HÍDRICOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 15,
                'nome' => 'SEC. DO DESENVOLVIMENTO ECONOMICO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 16,
                'nome' => 'SEC. JUSTICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 17,
                'nome' => 'SEC. PLANEJ. CIENCIA E TECNOLOGIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 1011,
                'nome' => 'SEC. RECURSOS HIDRICOS SAN. E HABIT.',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 19,
                'nome' => 'SEC. SAUDE',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 20,
                'nome' => 'SEC. SEGURANCA PUBLICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 21,
                'nome' => 'SEC. TRABALHO E ACAO SOCIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 8,
                'nome' => 'SECOM - SEC. DE COMUNICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 88,
                'nome' => 'SECRETARIA DE PROMOÇÃO DA IGUALDADE RACIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 37,
                'nome' => 'SEI-SUPERINT. DE ESTUDOS ECONOMICOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 68,
                'nome' => 'SUCAB-SUPERINT. DE CONSTRUCAO ADM BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 69,
                'nome' => 'SUDESB-SUPERINT. DE DESPORTOS DO EST. DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 70,
                'nome' => 'SUDIC-SUPERINT. DESENV. INDUSTRIAL E COMERCIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 1010,
                'nome' => 'SUP. DE GEOLOGIA E RECURSOS MINERAIS',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 74,
                'nome' => 'UNIVERSIDADE DO ESTADO DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 71,
                'nome' => 'UNIVERSIDADE EST. DE FEIRA DE SANTANA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 73,
                'nome' => 'UNIVERSIDADE EST. DE SANTA CRUZ',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 72,
                'nome' => 'UNIVERSIDADE ESTADUAL DO SUDOESTE DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 501,
                'nome' => 'CASA CIVIL - Casa Civil da Pref. Munic. Salvador',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 530,
                'nome' => 'CGM - CONTROLADORIA GERAL DO MUNICIPIO',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 560,
                'nome' => 'COGEL - Companhia de Governanca Eletron de Salvador',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 549,
                'nome' => 'COHAB - Companhia Municipal de Habitacao',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 570,
                'nome' => 'DESAL - Comp de Desenvolv Urbano de Salvador',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 577,
                'nome' => 'FCM - Fundacao Cidade Mae',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 562,
                'nome' => 'FGM - Fundacao Gregorio de Matos',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 569,
                'nome' => 'FMLF - Fundacao Mario Leal Ferreira',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 597,
                'nome' => 'FUMPRES CAM-FUNDO MUNIC DE PREVIDENCIA DO SERVIDOR',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 596,
                'nome' => 'FUMPRES INA-FUNDO MUNIC DE PREVIDENCIA DO SERVIDOR',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 588,
                'nome' => 'GABP - Gabinete do Prefeito',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 524,
                'nome' => 'GABVP - Gabinete Vice Prefeito',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 555,
                'nome' => 'LIMPURB - Empresa de Limpeza Urbana do Salvador',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 508,
                'nome' => 'PGMS - Proc. Geral do Municipio de Salvador',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 565,
                'nome' => 'PREVIS ATIVO - Instituto de Previdencia do Salvador',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 576,
                'nome' => 'PREVIS CAMARA - Instit de Previd do Salvador - Camara',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 575,
                'nome' => 'PREVIS INATIVO - Instituto de Previdencia do Salvador',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 561,
                'nome' => 'SALTUR - Empresa Salvador Turismo',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 586,
                'nome' => 'SECIS - Secretaria Cidade Sustentavel',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 595,
                'nome' => 'SECOM - SECRETARIA MUNICIPAL DE COMUNICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 587,
                'nome' => 'SEDES - Sec Mun do Desenvolv Turismo e Cultura',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 591,
                'nome' => 'SEDUR',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 503,
                'nome' => 'SEFAZ - Secretaria Municipal da Fazenda',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 592,
                'nome' => 'SEMAN - Secretaria de Manuten',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 502,
                'nome' => 'SEMGE - Secretaria Municipal de Gestao',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 522,
                'nome' => 'SEMOB - Secretaria de Mobilidade',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 513,
                'nome' => 'SEMOP - Secretaria Municipal de Ordem Publica',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 527,
                'nome' => 'SEMPS - Sec Mun Prom Social Combate a Pobreza',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 593,
                'nome' => 'SEMTEL - SEC MUNIC DO TRABALHO ESPORTE E LAZER',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 525,
                'nome' => 'SEMUR - Secretaria Municipal de Reparacao',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 526,
                'nome' => 'SINDEC - Sec. Municipal da Infraestrutura Defesa Civil',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 504,
                'nome' => 'SMED - Secretaria Municipal de Educacao',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 505,
                'nome' => 'SMS - Secretaria Municipal de Saude',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 583,
                'nome' => 'SPM - Superint Especial Politica para Mulheres',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 568,
                'nome' => 'SUCOM - Sup de Contr e Ord Uso Solo do Municipio',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 563,
                'nome' => 'SUCOP - Sup de Conserv e Obras Pub do Salvador',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 571,
                'nome' => 'SUSPREV - Guarda Municipal de Salvador',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 573,
                'nome' => 'TRANSALVADOR - Superint de Transito Transp do Salvador',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 558,
                'nome' => 'TRANSUR - Empresa de Transportes Urbanos',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 25,
                'nome' => 'CASA CIVIL',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 4,
                'nome' => 'CORPO DE BOMBEIRO MILITAR DO ESP',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 3,
                'nome' => 'DEFENSORIA P',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 8,
                'nome' => 'DEPARTAMENTO DE EDIFICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 33,
                'nome' => 'DEPARTAMENTO DE ESTRADAS DE RODAGEM DO ESPIRITO SANTO',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 35,
                'nome' => 'DEPARTAMENTO ESTADUAL DE TRANSITO',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 41,
                'nome' => 'FACULDADE DE M',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 24,
                'nome' => 'Fundo de Prev.Servidores Publico Civil e Militar',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 755,
                'nome' => 'HOSPITAL POL',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 28,
                'nome' => 'IPAJM - INST PREV ASSIST SERV ESP SANTO',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 7,
                'nome' => 'POLICIA MILITAR DO ESP',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 6,
                'nome' => 'POL',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 27,
                'nome' => 'Procuradoria Geral do Estado',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 9,
                'nome' => 'SEC. SEGURAN',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 0,
                'nome' => 'SEC. TRABALHO  E A',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 10,
                'nome' => 'SECRETARIA DE ESTADO DA CASA CIVIL',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 12,
                'nome' => 'SECRETARIA DE ESTADO DA CULTURA',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 13,
                'nome' => 'SECRETARIA DE ESTADO DA EDUCA',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 14,
                'nome' => 'SECRETARIA DE ESTADO DA FAZENDA',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 15,
                'nome' => 'SECRETARIA DE ESTADO DA JUSTI',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 16,
                'nome' => 'SECRETARIA DE ESTADO DA SA',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 22,
                'nome' => 'SECRETARIA DE ESTADO DE ASSISTENCIA SOCIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 2,
                'nome' => 'SECRETARIA DE ESTADO DE CONTROLE E TRANSPARENCIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 23,
                'nome' => 'SECRETARIA DE ESTADO DE ECONOMIA E PLANEJAMENTO',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 20,
                'nome' => 'SECRETARIA DE ESTADO DO GOVERNO',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 19,
                'nome' => 'SECRETARIA DE ESTADO DOS TRANSPORTES E OB...',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 21,
                'nome' => 'SEDETUR',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 11,
                'nome' => 'SEDU-GRUPO ADMISTRATIVO SETORIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 26,
                'nome' => 'SEGER- SECRETARIA DE ESTADO DE GEST',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 29,
                'nome' => 'Sec. Educac',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 17,
                'nome' => 'Sec. Plan. Or',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 30,
                'nome' => 'Sec. de Est. Desen. Economico e Turismo',
                'ativo' => true,
            ],
            [
                'id_origem' => 6,
                'cod_orgao' => 18,
                'nome' => 'TC-TRIBUNAL DE CONTAS',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1001,
                'nome' => 'BAHIATURSA',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1102,
                'nome' => 'CIA DE DESENVOL. DE ACAO REGIONAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1003,
                'nome' => 'CIA DE ENGENHARIA RURAL DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1005,
                'nome' => 'CIA DESENVOLV. URBANO DO ESTADO DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 65,
                'nome' => 'CIA PROCESSAMENTO DADOS EST. DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1004,
                'nome' => 'CM-CAMARA MUNICIPAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1006,
                'nome' => 'EBDA-P. BAIANA DE DESENVOLV. AGRICULA',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 597,
                'nome' => 'FUNDO MUNICIPAL DE PREVIDENCIA - FUMPRES -CAM',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1007,
                'nome' => 'IPRAJ-INST. PEDRO RIBEIRO DE ADM. JUDICIARIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1008,
                'nome' => 'JM-JUIZADO DE MENORES',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1009,
                'nome' => 'MP-MINISTERIO PUBLICO',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 2017,
                'nome' => 'POTENCIAIS - TJ',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1012,
                'nome' => 'TCE-TRIBUNAL DE CONTAS DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1013,
                'nome' => 'TCM-TRIBUNAL DE CONTAS DO MUNICIPIO',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1014,
                'nome' => 'TJ-TRIBUNAL DE JUSTICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1016,
                'nome' => 'TRE-TRIBUNAL REGIONAL ELEITORAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 12,
                'cod_orgao' => 1015,
                'nome' => 'TRT-TRIBUNAL REGIONAL DO TRABALHO',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 9,
                'nome' => 'Departamento de Infra. Rod. de Sergipe',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 13,
                'nome' => 'Secretaria da Agricultura e Desenvolvimento Rural',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 21,
                'nome' => 'Procuradoria Geral do Estado',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 16,
                'nome' => 'Instituto de Promoção de Assistência à Saúde',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 4,
                'nome' => 'Funda&ccedil;&atilde;o Renascer',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 10,
                'nome' => 'Sergipe Previdência Aposentado',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 22,
                'nome' => 'Secretaria de Cultura',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 14,
                'nome' => 'Secretaria de Estado da Casa Civil',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 23,
                'nome' => 'Prefeitura Municipal de Aracaju',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 3,
                'nome' => 'Secretaria da Sa&uacute;de',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 1,
                'nome' => 'Secretaria de educa&ccedil;&atilde;o',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 2,
                'nome' => 'Secretaria da Fazenda',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 5,
                'nome' => 'Sergipe Previdência  Pens&atilde;o',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 6,
                'nome' => 'Secretaria de Seg. Publica',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 7,
                'nome' => 'Governo de Sergipe Pens&atilde;o',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 8,
                'nome' => 'Tribunal de Justiça',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 12,
                'nome' => 'Ministerio Publico',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 15,
                'nome' => 'Secretaria Estado do Planejamento Or&ccedil;amento e Gest&atilde;o',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 17,
                'nome' => 'Assembleia Legislativa de Segipe',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 18,
                'nome' => 'Secretaria de Est. da Justiça e de Def. Ao Consumidor',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 19,
                'nome' => 'Secretaria Estado da inclus&atilde;o e Ass. e Des. Social',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 20,
                'nome' => 'Instituto Tec. e de Pesq. do Estado de Sergipe',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 24,
                'nome' => 'Tribunal de Contas',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 25,
                'nome' => 'Prefeitura Municipal de Itabaianinha',
                'ativo' => true,
            ],
            [
                'id_origem' => 46,
                'cod_orgao' => 26,
                'nome' => 'Sec. de Est. Des. Econ. e da Ci&ecirc;ncia e Tecnologia',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 90,
                'nome' => 'FUNDO DE PROTEÇÃO SOCIAL DOS MILITARES  FPSM',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 2,
                'nome' => 'SEAGRI',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 3,
                'nome' => 'ENCARGOS GERAIS DO ESTADO - AL',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 4,
                'nome' => 'SEC. EDUCACAO',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 5,
                'nome' => 'IPASEAL - PENSOES',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 6,
                'nome' => 'SEC. SAUDE',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 7,
                'nome' => 'SEFAZ',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 8,
                'nome' => 'FUNGLAF',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 11,
                'nome' => 'SAGAB - SEC. P/ ASSUNTOS DO GABINETE CIVIL',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 12,
                'nome' => 'SEC - ESPORTE E CULTURA',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 13,
                'nome' => 'DER - DEP. DE ESTRADAS DE RODAGEM',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 14,
                'nome' => 'SEPLAN-SEC. DO PLANEJAMENTO E DESENV.',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 15,
                'nome' => 'FUNGLAF INATIVOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 16,
                'nome' => 'GABINETE MILITAR DO GOVERNADOR',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 17,
                'nome' => 'IMA - INSTITUTO DO MEIO AMBIENTE',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 18,
                'nome' => 'CEPA',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 19,
                'nome' => 'CBM- CORPO DE BOMBEIROS',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 20,
                'nome' => 'FIPLAN-FUND. INSTITUTO',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 21,
                'nome' => 'PROCURADORIA GERAL DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 22,
                'nome' => 'SEC. ADM. PUBLICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 23,
                'nome' => 'SEC. JUSTICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 25,
                'nome' => 'SAS - SECRETARIA DE ASSISTENCIA SOCIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 26,
                'nome' => 'SEMPRE - SECRETARIA DE EMPREGO E RENDA E REL. TRAB.',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 27,
                'nome' => 'INSTITUTO ZUMBI DOS PALMARES',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 29,
                'nome' => 'CAMARA MUNICIPAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 30,
                'nome' => 'UNCISAL - FUND. UNIV. CIENC. SAUDE',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 10,
                'nome' => 'IPASEAL-ATIVOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 31,
                'nome' => 'SEARHP - Secretaria de Adm. Recursos Humanos e Patrimonio',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 9,
                'nome' => 'SECRETARIA DE DEFESA SOCIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 32,
                'nome' => 'SEC. GERAL DO GOVERNO',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 28,
                'nome' => 'SECRETARIA DE CIÊNCIA TECNOLIGIA E EDUCAÇÃO SUPERIOR',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 33,
                'nome' => 'SEC. COORD. DE JUSTIÇA E DEFESA SOCIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 34,
                'nome' => 'POLICIA CIVIL',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 35,
                'nome' => 'DETRAN',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 36,
                'nome' => 'CARHP',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 37,
                'nome' => 'Companhia Alagoana de Recursos Humanas e PAT',
                'ativo' => true,
            ],
            [
                'id_origem' => 7,
                'cod_orgao' => 1,
                'nome' => 'PM - AL',
                'ativo' => true,
            ],
            [
                'id_origem' => 21,
                'cod_orgao' => 1,
                'nome' => 'Prefeitura de Alagoinhas',
                'ativo' => true,
            ],
            [
                'id_origem' => 21,
                'cod_orgao' => 2,
                'nome' => 'CAMARA MUNICIPAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 49,
                'cod_orgao' => 0,
                'nome' => 'FUNDO MUNICPAL DE SAUDE DE POÇO REDONDO',
                'ativo' => true,
            ],
            [
                'id_origem' => 49,
                'cod_orgao' => 1,
                'nome' => 'ASSISTENCIAL SOCIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 49,
                'cod_orgao' => 3,
                'nome' => 'PREFEITURA',
                'ativo' => true,
            ],
            [
                'id_origem' => 50,
                'cod_orgao' => 1,
                'nome' => 'VERA CRUZ',
                'ativo' => true,
            ],
            [
                'id_origem' => 51,
                'cod_orgao' => 1,
                'nome' => 'PREFEITURA MUNICIPAL DE JAGUARARI',
                'ativo' => true,
            ],
            [
                'id_origem' => 52,
                'cod_orgao' => 1,
                'nome' => 'PREFEITURA PEDRAS DE FOGO',
                'ativo' => true,
            ],
            [
                'id_origem' => 53,
                'cod_orgao' => 1,
                'nome' => 'PREFEITURA MATRIZ CAMARAGIBE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 57,
                'nome' => 'HEMOLACEN',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 11,
                'nome' => 'SEC. GOVERNO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 12,
                'nome' => 'VICE GOVERNADORIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 14,
                'nome' => 'SEPL',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 15,
                'nome' => 'SECRETARIA DA ADMINISTRACAO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 16,
                'nome' => 'SEC. FAZENDA',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 17,
                'nome' => 'SEC. ADM',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 18,
                'nome' => 'SEC. EDUCACAO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 20,
                'nome' => 'SEC. DA SAUDE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 22,
                'nome' => 'SEC. DE EST.DA SEGURANCA PUBLICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 23,
                'nome' => 'SEC. DO EST. DOS TRANP. E ENERG.',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 27,
                'nome' => 'SEC DO EST. DA CULTURA',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 29,
                'nome' => 'SEC. DE AÇÃO SOCIAL E DO TRABALHO DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 36,
                'nome' => 'COORD. GERAL DO EST.',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 37,
                'nome' => 'PROCURADORIA GERAL DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 38,
                'nome' => 'SEC. DE EST. DA JUSTICA E DA CIDADANIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 39,
                'nome' => 'CASA CIVIL / SECOM',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 46,
                'nome' => 'DEFENSORIA PÚBLICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 49,
                'nome' => 'SEC. EST. ADMINISTRAÇÃO/ APOSENTADOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 52,
                'nome' => 'DEPARTAMENTO DE ESTRADAS DE RODAGEM',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 53,
                'nome' => 'DEP. EST. DE TRANSITO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 54,
                'nome' => 'SECRETARIA DA ADMINISTRACAO DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 56,
                'nome' => 'INST. DE PREV. DO ESTADO DE SERGIPE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 58,
                'nome' => 'INST. TECNOLOGIA PESQUISA DE SERGIPE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 59,
                'nome' => 'JUCESE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 61,
                'nome' => 'FUNDAÇÃO RENASCER DO ESTADO DE SERGIPE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 63,
                'nome' => 'FUNDESP',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 65,
                'nome' => 'FUND. DE DESENV. COMUNITÁRIO DE SERGIPE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 68,
                'nome' => 'SEGRASE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 72,
                'nome' => 'COHIDRO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 84,
                'nome' => 'POLICIA MILITAR/ BOMBEIRO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 88,
                'nome' => 'SEC. EST. ADMINISTRAÇÃO/ BOMBEIROS REFORMADOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 89,
                'nome' => 'SEC. EST. ADMINISTRAÇÃO/  REFORMADOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 92,
                'nome' => 'DEPARTAMENTO DE ESTRADAS E RODAGEM/ APOSENTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 93,
                'nome' => 'IPES',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 100,
                'nome' => 'TCE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 101,
                'nome' => 'DETRAN/ SERGIPE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 102,
                'nome' => 'ASSEMBLÉIA LEGISLATIVA',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 103,
                'nome' => 'FUNDAP',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 104,
                'nome' => 'FUNDEF',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 105,
                'nome' => 'DEAGRO-DEPART. DE desenvolvimento agropecario sergipe',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 106,
                'nome' => 'HEMOSE',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 107,
                'nome' => 'SECPAST',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 108,
                'nome' => 'SETUR',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 109,
                'nome' => 'SEC. DA EDUCAÇÃO- INATIVO',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 110,
                'nome' => 'Plano de assistencia a saude do estado de sergipe',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 83,
                'nome' => 'POLICIA MILITAR',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 10,
                'nome' => 'CASA CIVIL',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 111,
                'nome' => 'TRIBUNAL DE CONTAS',
                'ativo' => true,
            ],
            [
                'id_origem' => 3,
                'cod_orgao' => 112,
                'nome' => 'ASSIST. DE SERV. ADM',
                'ativo' => true,
            ],
            [
                'id_origem' => 13,
                'cod_orgao' => 1,
                'nome' => 'PREFEITURA  MUNICIPAL DE JOAO PESSOA',
                'ativo' => true,
            ],
            [
                'id_origem' => 13,
                'cod_orgao' => 2,
                'nome' => 'SUPERINTENDÊNCIA DE TRANSPORTE E TRANSITO',
                'ativo' => true,
            ],
            [
                'id_origem' => 13,
                'cod_orgao' => 3,
                'nome' => 'EMLUR',
                'ativo' => true,
            ],
            [
                'id_origem' => 13,
                'cod_orgao' => 6,
                'nome' => 'EMATER',
                'ativo' => true,
            ],
            [
                'id_origem' => 13,
                'cod_orgao' => 7,
                'nome' => 'PREFEITURA MUNICIPAL DE JOAO PESSOA - INATIVO',
                'ativo' => true,
            ],
            [
                'id_origem' => 13,
                'cod_orgao' => 4,
                'nome' => 'CÂMARA MUNICIPAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 13,
                'cod_orgao' => 5,
                'nome' => 'INSTITUTO CÂNDIDA VARGAS',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 43,
                'nome' => 'SEC. EST. CIE TEC M. A',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 45,
                'nome' => 'SEC. EST. TUR DES. ECO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 47,
                'nome' => 'CASA CIVIL GOVERNADOR',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 61,
                'nome' => 'FUNDAC',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 42,
                'nome' => 'JUSTICA COMUM',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 49,
                'nome' => 'SEC. EST. JUV.ESP. LAZ',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 51,
                'nome' => 'SEC. EST. SEG. DEF. SOC.',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 53,
                'nome' => 'SEC. EST. PLANEJ. GEST.',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 54,
                'nome' => 'SEC. EST. DES. AGR. PES',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 55,
                'nome' => 'PBPREV - INATIVOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 56,
                'nome' => 'SECRETARIA DE ESPORTE E LAZER',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 57,
                'nome' => 'INTERPA- Instituto de Terras da Paraíba',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 58,
                'nome' => 'SEC. ESTADO COM INST',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 59,
                'nome' => 'SEC. EST. ARTIC. GOV',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 60,
                'nome' => 'LOTEP. LOTERIA DO ESTADO DA PARAIBA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 62,
                'nome' => 'SEC. RECUR. HIDRIC. E MINERAIS',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 63,
                'nome' => 'SEC ESTADO RECEITA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 64,
                'nome' => 'PRESTAÇÃO DE SERVICO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 65,
                'nome' => 'PIEMTUR',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 1,
                'nome' => 'UNIVERSIDADE ESTADUAL DA PARAIBA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 36,
                'nome' => 'CINEP- Companhia de Desenvolvimento da Paraíba',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 44,
                'nome' => 'SEC. EST. DESENV. HUM',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 46,
                'nome' => 'SEC. EST. EDUC. CULTURAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 48,
                'nome' => 'SEC. EST. ADM. PENIT',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 50,
                'nome' => 'SEC. EST. DA SAUDE',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 52,
                'nome' => 'CONTROLADORIA GERAL DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 35,
                'nome' => 'CAGEPA- Companhia de Água e Esgotos da Paraíba',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 2,
                'nome' => 'POLICIA MILITAR',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 3,
                'nome' => 'SEC ADMINISTRAÇÃO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 5,
                'nome' => 'ASSEMBLEIA LEGISLATIVA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 6,
                'nome' => 'DEFENS. PUBLICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 7,
                'nome' => 'ENC.GERAIS DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 8,
                'nome' => 'SEC EXT COMUN INST',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 9,
                'nome' => 'SEC. IRRIG. ABAST.',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 10,
                'nome' => 'GABINETE CIVIL',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 11,
                'nome' => 'SEC.CIDAD. JUSTIÇA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 12,
                'nome' => 'GAB DO VICE - GOVERNADOR',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 13,
                'nome' => 'SEC.SEGR. PUBLICA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 4,
                'nome' => 'SEC EDUCAÇÃO E CULTURA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 14,
                'nome' => 'PENSÃO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 15,
                'nome' => 'SEC SAUDE',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 16,
                'nome' => 'ENGARGO PESSOAL REFORMADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 17,
                'nome' => 'CONSELHO PENITÊNCIARIO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 19,
                'nome' => 'GABINETE MILITAR',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 20,
                'nome' => 'PROC. GERAL DO ESTADO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 21,
                'nome' => 'SEC DAS FINANÇAS',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 22,
                'nome' => 'SEC DO PLANEJAMENTO E COORD. GERAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 23,
                'nome' => 'SEC DA AGRICULTURA E ABASTECIMENTO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 24,
                'nome' => 'SEC DA INDUSTRIA E COMERCIO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 25,
                'nome' => 'SEC INTERIOR E JUSTIÇA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 26,
                'nome' => 'SEC DO SERVIÇO SOCIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 27,
                'nome' => 'SEC DE TRANSPORTES E OBRAS',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 28,
                'nome' => 'SEC DAS MINAS E ENERGIA E MEIO AMBIENTE',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 29,
                'nome' => 'SEC DA INFRAESTRUTURA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 30,
                'nome' => 'ESCRITORIO DE REPRESENTAÇÃO DOS ESTADOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 31,
                'nome' => 'PROCURADORIA DA ASSISTÊNCIA JUDICIARIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 32,
                'nome' => 'SEC ESPORTE E TURISMO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 33,
                'nome' => 'SEC PLANEJAMENTO',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 34,
                'nome' => 'SEC DO TRABALHO E ACAO SOCIAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 37,
                'nome' => 'DEPARTAMENTO ESTADUAL DE TRANSITO DETRAN',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 39,
                'nome' => 'SEC. RECEITA ESTADUAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 40,
                'nome' => 'PBPREV',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 67,
                'nome' => 'SEC. MEIO AMB. E REC. HIDRICOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 68,
                'nome' => 'SEC. ACOMPANHAN. ACOES GOVERNAM',
                'ativo' => true,
            ],
            [
                'id_origem' => 15,
                'cod_orgao' => 69,
                'nome' => 'A UNIÃO',
                'ativo' => true,
            ],
            [
                'id_origem' => 16,
                'cod_orgao' => 1,
                'nome' => 'PREF MUNICIPAL DE JUAZEIRO',
                'ativo' => true,
            ],
            [
                'id_origem' => 26,
                'cod_orgao' => 1,
                'nome' => 'PREFEITURA DE JEQUIÉ',
                'ativo' => true,
            ],
            [
                'id_origem' => 26,
                'cod_orgao' => 2,
                'nome' => 'PREFEITURA DE JEQUIÉ - PENCIONISTAS E INATIVOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 43,
                'cod_orgao' => 1,
                'nome' => 'CONVÊNIO PARAIBA',
                'ativo' => true,
            ],
            [
                'id_origem' => 45,
                'cod_orgao' => 1004,
                'nome' => 'CM-CAMARA MUNICIPAL',
                'ativo' => true,
            ],
            [
                'id_origem' => 55,
                'cod_orgao' => 1,
                'nome' => 'PREFEITURA MUNICIPAL DE AURELINO LEAL - BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 54,
                'cod_orgao' => 2,
                'nome' => 'PREFEITURA MUNICIPAL DE GUANAMBI',
                'ativo' => true,
            ],
            [
                'id_origem' => 56,
                'cod_orgao' => 1,
                'nome' => 'PREFEITURA DE NOSSA SENHORA DAS DORES - SE',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 2,
                'nome' => 'SEC. ADMINISTRAÇÃO PENITENCIÁRIA E RESSOCIALIZAÇÃO',
                'ativo' => true,
            ],
            [
                'id_origem' => 21,
                'cod_orgao' => 3,
                'nome' => 'SESAU – SECRETARIA MUNICIPAL DE SAÚDE',
                'ativo' => true,
            ],
            [
                'id_origem' => 57,
                'cod_orgao' => 1,
                'nome' => 'SEC DE ADMINISTRAÇÃO',
                'ativo' => true,
            ],
            [
                'id_origem' => 57,
                'cod_orgao' => 2,
                'nome' => 'SEC DA SAÚDE',
                'ativo' => true,
            ],
            [
                'id_origem' => 57,
                'cod_orgao' => 3,
                'nome' => 'SEC DA EDUCAÇÃO',
                'ativo' => true,
            ],
            [
                'id_origem' => 57,
                'cod_orgao' => 4,
                'nome' => 'SMTT',
                'ativo' => true,
            ],
            [
                'id_origem' => 57,
                'cod_orgao' => 5,
                'nome' => 'GUARDA MUNICIPAL',
                'ativo' => 1,
            ],
            [
                'id_origem' => 47,
                'cod_orgao' => 1,
                'nome' => 'PREFEITURA MUNICIPAL DE MONTE ALEGRE',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 92,
                'nome' => 'SEC. DE ASSISTENCIA E DESENVOLVIMENTO SOCIAL DA BAHIA',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 94,
                'nome' => 'TCE - APOSENTADOS',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 590,
                'nome' => 'SECULT - SECRETARIA MUNICIPAL DE CULTURA E TURISMO',
                'ativo' => true,
            ],
            [
                'id_origem' => 2,
                'cod_orgao' => 26,
                'nome' => 'SEC. DE DESENVOLVIMENTO URBANO - SEDUR',
                'ativo' => true,
            ],
            [
                'id_origem' => 4,
                'cod_orgao' => 598,
                'nome' => 'SEMAN – SECRETARIA MUNICIPAL DE MANUTENçãO DA CIDADE',
                'ativo' => true,
            ],
            [
                'id_origem' => 57,
                'cod_orgao' => 6,
                'nome' => 'SECRETARIA MUNICIPAL DA FAZENDA - SEMFAZ',
                'ativo' => true,
            ],
        ];

        $origens = Origem::pluck('id', 'cod_local');

        $orgaos = collect($orgaos)
            ->map(function ($orgao) use ($origens) {
                return [
                    'id_origem' => $origens[$orgao['id_origem']],
                    'cod_orgao' => $orgao['cod_orgao'],
                    'nome' => $orgao['nome'],
                    'ativo' => $orgao['ativo'],
                ];
            })
            ->toArray();

        Orgao::upsert($orgaos, ['id_origem', 'cod_orgao'],
            ['nome', 'ativo']);
    }
}
